# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a9a33d9c5f4a9dbc45b80563874fc9f0580be3f882406c60b15a1b1618f1150f2a09b9f08c358660b535cc575b238372f583b17209489718bc571828d81e9c7

test:
  secret_key_base: b78b241c63712a78c18740e8e8dd2091e18139934952d7d767eeeb5239348819d209d065ff334fbf7f009718fb7d1217ba8d762f9cea00d98f319a9444b73970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
